#!/bin/sh

#mv /usr/share/meegotouch/applicationextensions/sysuid-screenlock.desktop /usr/share/meegotouch/applicationextensions/sysuid-screenlock-nokia.desktop
#ln -s /opt/widgets/screenlock/share/meegotouch/applicationextensions/sysuid-screenlock.desktop /usr/share/meegotouch/applicationextensions/sysuid-screenlock.desktop

#initctl restart xsession/sysuid
